*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ CHECK_SUPPORTED_FIELD

         IMPORTING
               VALUE(TABNAME) LIKE !DFIES-TABNAME
               VALUE(FIELDNAME) LIKE !DFIES-FIELDNAME
         EXCEPTIONS
!NOT_SUPPORTED .