*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LNDSEU01.   "CHECK_SUPPORTED_FIELD
INCLUDE LNDSEU02.   "CONVERT_SELECT_INTO_WHERE
INCLUDE LNDSEU03.   "GET_KEY_FIELDS_OF_TABLE